CREATE TABLE families (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50) NOT NULL,
    updated_by VARCHAR(50) NOT NULL,
    UNIQUE INDEX idx_slug (slug)
);

CREATE TABLE genera (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    description TEXT,
    family_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50) NOT NULL,
    updated_by VARCHAR(50) NOT NULL,
    UNIQUE INDEX idx_slug (slug),
    INDEX idx_family_id (family_id),
    FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE SET NULL
);

INSERT INTO families (name, slug, description, created_at, updated_at, created_by, updated_by) VALUES
('Fabaceae', 'fabaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Polygonaceae', 'polygonaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Apocynaceae', 'apocynaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Rubiaceae', 'rubiaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Asteraceae', 'asteraceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Lamiaceae', 'lamiaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Poaceae', 'poaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Apiaceae', 'apiaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Zingiberaceae', 'zingiberaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Cucurbitaceae', 'cucurbitaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Moraceae', 'moraceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Solanaceae', 'solanaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Rosaceae', 'rosaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Rutaceae', 'rutaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Euphorbiaceae', 'euphorbiaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Malvaceae', 'malvaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Amaranthaceae', 'amaranthaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Acanthaceae', 'acanthaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Verbenaceae', 'verbenaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Araceae', 'araceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Lythraceae', 'lythraceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Combretaceae', 'combretaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Myrtaceae', 'myrtaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Sapindaceae', 'sapindaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Ranunculaceae', 'ranunculaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Papaveraceae', 'papaveraceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Brassicaceae', 'brassicaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Capparaceae', 'capparaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Meliaceae', 'meliaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Anacardiaceae', 'anacardiaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Vitaceae', 'vitaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Tiliaceae', 'tiliaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Oxalidaceae', 'oxalidaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Geraniaceae', 'geraniaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Scrophulariaceae', 'scrophulariaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Bignoniaceae', 'bignoniaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Pedaliaceae', 'pedaliaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Plantaginaceae', 'plantaginaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Nyctaginaceae', 'nyctaginaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Amaryllidaceae', 'amaryllidaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Liliaceae', 'liliaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Asparagaceae', 'asparagaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Lauraceae', 'lauraceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Piperaceae', 'piperaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Aristolochiaceae', 'aristolochiaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Menispermaceae', 'menispermaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Annonaceae', 'annonaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Myristicaceae', 'myristicaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Magnoliaceae', 'magnoliaceae', NULL, NOW(), NOW(), 'admin', 'admin'),
('Santalaceae', 'santalaceae', NULL, NOW(), NOW(), 'admin', 'admin');

